### ISSUE TITLE
Heroku: XMLHttpRequest blocked; content must be served over HTTPS

### ISSUE THREAD

**Issue by Andras1000** [flyingsparx/FlaskDirectUploader#10]
I deployed this to Heroku and get the "Could not get signed URL." pop-up window after trying to upload a picture.

The console has: 

`Mixed Content: The page at 'https://xxxx.herokuapp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxx.herokuapp.com/sign-s3/?file-name=myimage.jpg&file-type=image/jpeg'. This request has been blocked; the content must be served over HTTPS.`

**Comment by willwebberley** [comment]
Your JavaScript code is trying to make a request using a different protocol to the one used to load the page itself.

To fix this, ensure you are making your request over HTTPS on [this line](https://github.com/flyingsparx/FlaskDirectUploader/blob/master/templates/account.html#L65).

**Comment by Andras1000** [comment]
Thanks for the quick response. 

After fixing the other issue with 400 Bad Request this bit works as well now. There was no need to change anything.
