### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by paolop3n** [flyingsparx/FlaskDirectUploader#7]
Hi,

I have followed your example using Django as framework and Python version 2.7.4.
The bucket is created in the region "eu-west-1" (Ireland), with the setup that you recommend.

But when I try to read the url generated I receive the following error: 
<Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

The credentials I am using have Administrator Access.

Could you please help me?
Thanks.

**Comment by maninp** [comment]
@paolop3n I've also experienced with same issue. After investigating long time, found solution by checking following case:

1. Did you add grantee for bucket?
2. Did you add permission for access key ?
3. Did you add policy for accessing bucket?(I did mistake here).
