### ISSUE TITLE
Get progress of upload

### ISSUE THREAD

**Issue by albydeca** [flyingsparx/FlaskDirectUploader#8]
Hi,

Thanks for making this companion repo. It made my life easier!

I'd like to add some kind of progress indication of the upload since I'm uploading large ZIP files. Is it possible to achieve this using the format laid out in this repo?

Thanks,
Alberto

**Comment by flyingsparx** [comment]
Hi,

I haven't looked into this properly myself, but you could try using the `XMLHttpRequest`'s `progress` listener ([see documentation](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress)).

This should work as long as the event object passed to the listener function knows both its `total` and `loaded` fields - though I haven't had a chance to test this yet to see!

**Comment by willwebberley** [comment]
Hi,

I haven't looked into this properly myself, but you could try using the XMLHttpRequest's progress listener ([see documentation](https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress)).

This should work as long as the event object passed to the listener function knows both its total and loaded fields - though I haven't had a chance to test this yet to see! For the upload progress, remember to bind the event to the `XMLHttpRequest.upload` object as mentioned in the docs.

**Comment by albydeca** [comment]
ok thanks, I'll try it out! Thanks for the direct docs link too!

**Comment by albydeca** [comment]
I can get the percentage of upload progress! Closing
