### ISSUE TITLE
POST https://<bucket>.s3.amazonaws.com/ 400 (Bad Request) error

### ISSUE THREAD

**Issue by JainVikas** [flyingsparx/FlaskDirectUploader#9]
I downloaded the whole source file as it is and just pushed the same to heroku without any changes, getting Bad request error.

I have verified S3 Cors configuration as well, it is correct.

**Comment by willwebberley** [comment]
It's hard to diagnose your problem without knowing more information. Below are some things you might want to check.

* Make sure you are authenticating correctly (i.e. verify that the AWS credentials you are using are actually working, being loaded correctly, and have the correct IAM policies for the task. Do this by using `boto` to perform other requests - such as listing a bucket's contents - directly to make sure everything is working before proceeding.)
* Check the contents of the response to see if there's any indication of the problem there.
* Check the name of the file you're uploading does not contain any strange characters that need to be cleaned
* Ensure the `file_name` and `file_type` vars are being correctly read on the server
* Check if you need to explicitly set your AWS region (see [this article](http://boto3.readthedocs.io/en/latest/guide/configuration.html))
* Finally, check [this AWS page](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html), which lists reasons why S3 might return a 400 status - stemming from invalid credentials through to too small/large files. See if your reason might be listed there?

**Comment by Andras1000** [comment]
I was also getting a 400 Bad Request despite cloning the app. 

The solution was to create a new S3 bucket in a different region (US East) instead of using the original EU (London) bucket. 

I am in London and the CORS Configuration was the same for both buckets.

**Comment by JainVikas** [comment]
@Mersaul4 Not yet, i didn't get time to try this again, Most probably today i will look again, and will also look at your solution.

**Comment by JainVikas** [comment]
on Further Exploration i noticed that for bad request, I get following message.
"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."
@Mersaul4 I guess when you changed you the bucket to US east, it supported the default mechanism
.
@flyingsparx  i was able to solve it in synchronous mode using the following command while creating a S3 resource  and using botcore:

from botocore.client import Config
s3 = boto3.resource('s3', aws_access_key_id= os.environ.get('AWS_ACCESS_KEY_ID'), aws_secret_access_key=os.environ.get('AWS_SECRET_ACCESS_KEY'),config=Config(signature_version='s3v4'))

Not sure how would i add while doing it through Ajax.  

Let me know if you need any further info for the same.

**Comment by willwebberley** [comment]
@Mersaul4 @JainVikas Some AWS regions require you use signature version 4 in order to authenticate your S3 request.

To do so, change [this line of your Python code](https://github.com/flyingsparx/FlaskDirectUploader/blob/master/application.py#L52) to be something along the lines of:

```python
s3 = boto3.client('s3', config=Config(signature_version='s3v4'))
```

(You will also need to import `Config` using `from botocore.client import Config` in your imports block).

There is more information on this in the [Boto documentation](http://boto3.readthedocs.io/en/latest/guide/s3.html#generating-presigned-urls).

Since this route executes in a result of the AJAX request, then this should solve your problem, @JainVikas, as you mentioned in your comment.

**Comment by JainVikas** [comment]
thanks, closing this.
